name: Continuous integration

on:
  push:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.73.0
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt install -y libasound2-dev libudev-dev
      - run: cargo check --all

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.73.0
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt install -y libasound2-dev libudev-dev
      - run: cargo test --all

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.73.0
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt install -y libasound2-dev libudev-dev
      - run: cargo clippy --all -- -D warnings
